### ISSUE TITLE
SOAP vs REST

### ISSUE THREAD

**Issue by ghost** [OZMOPOL/ozmoPol_BackEnd#1]
We will discuss here which one we should use. As a start I am putting a link for comparing these from stackoverflow.

http://stackoverflow.com/questions/19884295/soap-vs-rest-differences
@OZMOPOL/owners

**Comment by ghost** [comment]
We're gonna use RESTful Webservices using JAX-RS over MySQL.
Some useful links : https://netbeans.org/kb/docs/websvc/rest.html

@solsav @ugurcant

**Comment by soltanix** [comment]
RESTful all the way :smile:
