### ISSUE TITLE
EER Diagram

### ISSUE THREAD

**Issue by ghost** [OZMOPOL/ozmoPol_BackEnd#11]
@firatkaptan and @atharkh  can one of you please provide an EER diagram or a simple model from the latest changes in the database and upload it? We will need this information. (if you use standard softwares to generate it, that will be better)

**Comment by atharkh** [comment]
Ok, we will provide a model for database.

**Comment by firatkaptan** [comment]
hope it works https://github.com/OZMOPOL/Documentation/blob/master/Database%20Diagram.xlsx

**Comment by firatkaptan** [comment]
i uploadaded both pdf and workbench versions https://github.com/OZMOPOL/Documentation

**Comment by atharkh** [comment]
EER Diagrams are moved to a new folder, link is changed to:
https://github.com/OZMOPOL/Documentation/tree/master/EER%20Diagram
