### ISSUE TITLE
Product Backlog in wrong repo

### ISSUE THREAD

**Issue by soltanix** [OZMOPOL/ozmoPol_BackEnd#4]
Hey fellas,
I saw this "prodoct backlog" related file in backend dev repo. can someone put it in the appropriate place?

**Comment by soltanix** [comment]
for gods sake someone get this " Backlog.xlsx " file out of this repo! I dont know if you need this so, if you dont I can remove it!

**Comment by atharkh** [comment]
Abi, done! I removed it

**Comment by soltanix** [comment]
;D thanks :p
