### ISSUE TITLE
Repo Backup

### ISSUE THREAD

**Issue by soltanix** [OZMOPOL/ozmoPol_BackEnd#5]
Can someone also think of a way to backup our work, so incase something funny happens!

**Comment by ugurcant** [comment]
I thought GitHub can do this for us, just we should download from there in periodic time maybe once a week?

**Comment by atharkh** [comment]
when you commit your updates, the source will be change accordingly. we can have our backups saved by this link I guess.

https://backhub.co/

**Comment by soltanix** [comment]
tried it, couldnt work... its like its not functional. can you confirm that?

**Comment by atharkh** [comment]
I added all the repositories to my account and created a backup for all of them. I think it is working, also I found this, you may check it 
https://www.npmjs.com/package/github-backup
