### ISSUE TITLE
Votes by users for posts

### ISSUE THREAD

**Issue by atharkh** [OZMOPOL/ozmoPol_BackEnd#6]
Users' vote up-vote or down-vote for a post needed to be unique since a they can not vote for one post more than once. This issue had to be considered.

**Comment by ugurcant** [comment]
maybe we can create a "canVote" method to control it, it would save posts' ids who voted by user and when user wants to vote to post it would control the list and if it's not match it would let to vote otherwise it would print an error "you voted it before" or smt like that

**Comment by ugurcant** [comment]
If this solution okay for you I can work on "User can edit vote" issue or do you have any different suggestion I can also work on that too

**Comment by soltanix** [comment]
no this is not a good solution ugurcan,
athar, we fixed this issue didnt we?
 UNIQUE KEY user_vote_post (fk_vote_user_id, fk_vote_post_id)
this constraint makes it impossible for someone to vote for more than once on a specific post.
