### ISSUE TITLE
Deactivate account

### ISSUE THREAD

**Issue by ugurcant** [OZMOPOL/ozmoPol_BackEnd#9]
When someone wants to deactivate her/his account? will we delete it temporarly or just "sleep" this account?

**Comment by soltanix** [comment]
The option to put one's account to sleep requires a certain set of changes in the database, specifically putting an "account status" property for users. so everytime a query is made, it checks the value of that column. Having said all these, I dont know if we should implement this now... Lets see what others think.

**Comment by ghost** [comment]
We could use a property like "account status" as @solsav  said, and set it to Enabled or Disabled. There is no need to delete any data from database.
This applies to the posts and rooms too, when the related web-service is called we should check it's status to either return that post/room or not.

**Comment by soltanix** [comment]
there is only one problem with this: users are owners of the things they share, or create, so, if they want, the things they make (threads, posts, comments, rooms, links etc) should be deleted, ethically speaking. so ... lets put both functionalities (deactivation and deletion).
